version: "3.3"
services:
  service-apis:
    image: service-apis:1.0.1
    container_name: service-apis_v1.0.1
    build: ./
    env_file:
      - ./nodejs/.env
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs/:/app/
    #restart: always
