# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  service-apis

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  ServiceAPILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ServiceAPILayer
      Description: Service API nodejs dependencies
    CompatibleRuntimes:
      - nodejs12.x
      - nodejs14.x
      - nodejs16.x
    Metadata:
      BuildMethod: nodejs16.x
      BuildArchitecture: x86_64
    RetentionPolicy: Retain

  ServiceAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs/api/
      Handler: app.lambdaHandler
      Layers:
        - !Ref ServiceAPILayer
      Runtime: nodejs16.x
      Events:
        ApiEvents:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any
      VpcConfig:
        SecurityGroupIds:
          - sg-0f066bb84ae0aad33
        SubnetIds:
          - subnet-0b314802eac03bdcf
          - subnet-09c2baa68ca618189
          - subnet-0384c938c2920cd44

Outputs:
  ServiceAPI:
    Description: "API Gateway endpoint URL for Prod stage of Service API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  ServiceAPIFunction:
    Description: "Service API Lambda Function ARN for Service API"
    Value: !GetAtt ServiceAPIFunction.Arn
  ServiceFunctionIamRole:
    Description: "Implicit IAM Role for Service API"
    Value: !GetAtt ServiceAPIFunctionRole.Arn

