--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3 (Debian 15.3-1.pgdg120+1)
-- Dumped by pg_dump version 15.3

-- Started on 2023-12-01 07:32:06 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


--
-- TOC entry 6 (class 2615 OID 29602)
-- Name: sample; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA sample;


SET default_tablespace = '';

SET default_table_access_method = heap;


--
-- TOC entry 216 (class 1259 OID 29603)
-- Name: employee; Type: TABLE; Schema: sample; Owner: -
--

CREATE TABLE sample.employee (
    employee_id bigint NOT NULL,
    department_id bigint NOT NULL,
    employee_name character varying(150) NOT NULL,
    employee_email character varying(250) NOT NULL,
    employee_age smallint NOT NULL,
    employee_post character varying(150) NOT NULL,
    employee_basic integer NOT NULL,
    joining_date timestamp without time zone NOT NULL,
    status boolean NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 29608)
-- Name: Employee_employee_id_seq; Type: SEQUENCE; Schema: sample; Owner: -
--

ALTER TABLE sample.employee ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sample."Employee_employee_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 29609)
-- Name: company; Type: TABLE; Schema: sample; Owner: -
--

CREATE TABLE sample.company (
    company_id bigint NOT NULL,
    company_name character varying(50) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 29612)
-- Name: company_company_id_seq; Type: SEQUENCE; Schema: sample; Owner: -
--

ALTER TABLE sample.company ALTER COLUMN company_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sample.company_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 29613)
-- Name: department; Type: TABLE; Schema: sample; Owner: -
--

CREATE TABLE sample.department (
    department_id bigint NOT NULL,
    company_id bigint NOT NULL,
    department_name character varying(50) NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 29616)
-- Name: department_department_id_seq; Type: SEQUENCE; Schema: sample; Owner: -
--

ALTER TABLE sample.department ALTER COLUMN department_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sample.department_department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 29617)
-- Name: sales; Type: TABLE; Schema: sample; Owner: -
--

CREATE TABLE sample.sales (
    sales_id bigint NOT NULL,
    product_name character varying(50) NOT NULL,
    price double precision NOT NULL,
    customer_name character varying(150) NOT NULL,
    sales_person_id bigint NOT NULL,
    sale_date timestamp without time zone NOT NULL
);


--
-- TOC entry 3401 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN sales.product_name; Type: COMMENT; Schema: sample; Owner: -
--

COMMENT ON COLUMN sample.sales.product_name IS '{"Validations": {"StringLengthValidation": {"params":{"min":2, "max":50}, "msg":"Length must be between 2 to 50"} }}';


--
-- TOC entry 223 (class 1259 OID 29620)
-- Name: sales_sales_id_seq; Type: SEQUENCE; Schema: sample; Owner: -
--

ALTER TABLE sample.sales ALTER COLUMN sales_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sample.sales_sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 30162)
-- Name: user_profile; Type: TABLE; Schema: sample; Owner: -
--

CREATE TABLE sample.user_profile (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    pic character varying(128),
    password character varying(128) NOT NULL,
    email character varying(128) NOT NULL,
    employee_id bigint,
    active boolean,
    otp bigint,
    otp_expire_time timestamp without time zone,
    role character varying(20)
);


--
-- TOC entry 224 (class 1259 OID 30161)
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: sample; Owner: -
--

CREATE SEQUENCE sample.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- TOC entry 3402 (class 0 OID 0)
-- Dependencies: 224
-- Name: user_profile_id_seq; Type: SEQUENCE OWNED BY; Schema: sample; Owner: -
--

ALTER SEQUENCE sample.user_profile_id_seq OWNED BY sample.user_profile.id;


--
-- TOC entry 3225 (class 2604 OID 30165)
-- Name: user_profile id; Type: DEFAULT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.user_profile ALTER COLUMN id SET DEFAULT nextval('sample.user_profile_id_seq'::regclass);


--
-- TOC entry 3388 (class 0 OID 29609)
-- Dependencies: 218
-- Data for Name: company; Type: TABLE DATA; Schema: sample; Owner: -
--

INSERT INTO sample.company VALUES (1, 'The Sparrows');


--
-- TOC entry 3390 (class 0 OID 29613)
-- Dependencies: 220
-- Data for Name: department; Type: TABLE DATA; Schema: sample; Owner: -
--

INSERT INTO sample.department VALUES (1, 1, 'Finance');
INSERT INTO sample.department VALUES (2, 1, 'Sales');


--
-- TOC entry 3386 (class 0 OID 29603)
-- Dependencies: 216
-- Data for Name: employee; Type: TABLE DATA; Schema: sample; Owner: -
--

INSERT INTO sample.employee VALUES (1, 1, 'Martin Luther', 'martin.luther@e.mail', 32, 'Accountant', 155000, '2023-01-30 10:10:10', true);
INSERT INTO sample.employee VALUES (2, 1, 'Luke Cage', 'luke.cage@e.mail', 54, 'CFO', 399999, '2021-04-01 10:30:31', true);
INSERT INTO sample.employee VALUES (3, 2, 'Matt Murdock', 'matt.murdock@e.mail', 29, 'Sales Manager', 70000, '2020-07-15 10:30:31', true);
INSERT INTO sample.employee VALUES (7, 2, 'Foggy Nelson', 'foggy.nelson@e.mail', 27, 'Sr. Sales Representative', 40000, '2022-12-17 10:30:31', true);
INSERT INTO sample.employee VALUES (4, 2, 'Karen Page', 'karren.page@e.mail', 21, 'Sales Representative', 10000, '2022-08-01 10:30:31', true);


--
-- TOC entry 3392 (class 0 OID 29617)
-- Dependencies: 222
-- Data for Name: sales; Type: TABLE DATA; Schema: sample; Owner: -
--

INSERT INTO sample.sales VALUES (1, 'Note11', 50000, 'Steven Pollard', 4, '2023-10-10 10:10:10');
INSERT INTO sample.sales VALUES (2, 'Tab10', 75000, 'Olivia Grreen', 7, '2023-10-11 15:10:31');
INSERT INTO sample.sales VALUES (3, 'Ultrabook Zero1', 190000, 'Barry Allen', 4, '2023-10-11 17:15:51');


--
-- TOC entry 3395 (class 0 OID 30162)
-- Dependencies: 225
-- Data for Name: user_profile; Type: TABLE DATA; Schema: sample; Owner: -
--

INSERT INTO sample.user_profile VALUES (1, 'TestUser1', NULL, '17406e11c3af2ba6ebb2bc008b892892b73fc3e260eb6ef202794a8e507d0c1e', 'testuser1@email.com', 1, true, NULL, NULL, 'Manager');


--
-- TOC entry 3403 (class 0 OID 0)
-- Dependencies: 217
-- Name: Employee_employee_id_seq; Type: SEQUENCE SET; Schema: sample; Owner: -
--

SELECT pg_catalog.setval('sample."Employee_employee_id_seq"', 7, true);


--
-- TOC entry 3404 (class 0 OID 0)
-- Dependencies: 219
-- Name: company_company_id_seq; Type: SEQUENCE SET; Schema: sample; Owner: -
--

SELECT pg_catalog.setval('sample.company_company_id_seq', 1, true);


--
-- TOC entry 3405 (class 0 OID 0)
-- Dependencies: 221
-- Name: department_department_id_seq; Type: SEQUENCE SET; Schema: sample; Owner: -
--

SELECT pg_catalog.setval('sample.department_department_id_seq', 2, true);


--
-- TOC entry 3406 (class 0 OID 0)
-- Dependencies: 223
-- Name: sales_sales_id_seq; Type: SEQUENCE SET; Schema: sample; Owner: -
--

SELECT pg_catalog.setval('sample.sales_sales_id_seq', 11, true);


--
-- TOC entry 3407 (class 0 OID 0)
-- Dependencies: 224
-- Name: user_profile_id_seq; Type: SEQUENCE SET; Schema: sample; Owner: -
--

SELECT pg_catalog.setval('sample.user_profile_id_seq', 1, true);


--
-- TOC entry 3227 (class 2606 OID 29622)
-- Name: employee Employee_pkey; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.employee
    ADD CONSTRAINT "Employee_pkey" PRIMARY KEY (employee_id);


--
-- TOC entry 3229 (class 2606 OID 29624)
-- Name: company company_pkey; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (company_id);


--
-- TOC entry 3233 (class 2606 OID 29626)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (department_id);


--
-- TOC entry 3237 (class 2606 OID 29628)
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (sales_id);


--
-- TOC entry 3231 (class 2606 OID 29630)
-- Name: company unique_company_name_key; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.company
    ADD CONSTRAINT unique_company_name_key UNIQUE (company_name);


--
-- TOC entry 3235 (class 2606 OID 29632)
-- Name: department unique_department_name_key; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.department
    ADD CONSTRAINT unique_department_name_key UNIQUE (department_name);


--
-- TOC entry 3239 (class 2606 OID 30169)
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- TOC entry 3241 (class 2606 OID 29633)
-- Name: department fk_company; Type: FK CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.department
    ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES sample.company(company_id) NOT VALID;


--
-- TOC entry 3240 (class 2606 OID 29638)
-- Name: employee fk_department; Type: FK CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.employee
    ADD CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES sample.department(department_id) NOT VALID;


--
-- TOC entry 3242 (class 2606 OID 29643)
-- Name: sales fk_employee; Type: FK CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.sales
    ADD CONSTRAINT fk_employee FOREIGN KEY (sales_person_id) REFERENCES sample.employee(employee_id) NOT VALID;


--
-- TOC entry 3243 (class 2606 OID 30170)
-- Name: user_profile fk_user_profile_employees; Type: FK CONSTRAINT; Schema: sample; Owner: -
--

ALTER TABLE ONLY sample.user_profile
    ADD CONSTRAINT fk_user_profile_employees FOREIGN KEY (employee_id) REFERENCES sample.employee(employee_id);


-- Completed on 2023-12-01 07:32:06 UTC

--
-- PostgreSQL database dump complete
--
